
[package]
authors = ["Adeoye Adefemi <adefemiadeoye@yahoo.com>"]
description = "An Authentication, Authorization and Identity Management system for microservices"
edition = "2021"
name = "raccoon"
version = "0.1.3"

[workspace]
exclude = ["sandbox"]
members = ["raccoon_macros", "raccoon_mailer"]

[dependencies]
anyhow = "1.0.68"
async-graphql = {version = "4.0.6"}
async-session = "3.0.0"
async-trait = "0.1.57"
axum = {version = "0.5.16", features = ["headers", "json", "ws"]}
bcrypt = "0.13.0"
chrono = {version = "0.4.22", features = ["serde"]}
dotenv = "0.15.0"
futures = "0.3.23"
headers = "0.3.8"
http-body = "0.4.5"
hyper = { version = "0.14.25", features = ["full"] }
jsonwebtoken = "8.1.1"
lettre = "0.10.1"
oauth2 = "4.3.0"
once_cell = "1.15.0"
otp-rs = "0.1.1"
raccoon_macros = {path = "./raccoon_macros"}
raccoon_mailer = {path = "./raccoon_mailer"}
reqwest = {version = "0.11", default-features = false, features = [
  "rustls-tls",
  "json",
]}
serde = {version = "1.0.144", features = ["derive"]}
serde_json = "1.0.85"
sqlx = {version = "0.6.2", features = [
  "runtime-tokio-rustls",
  "postgres",
  "any",
  "uuid",
  "migrate",
  "chrono",
  "time",
]}
thiserror = "1.0.29"
time = "0.3.20"
tokio = {version = "1.20.1", features = ["full"]}
tower-http = {version = "0.3.4", features = ["cors", "fs", "trace"]}
tracing = "0.1.36"
tracing-subscriber = {version = "0.3", features = ["env-filter"]}
url = "2.3.1"
uuid = {version = "1.1.2", features = ["serde", "v4"]}
validator = {version = "0.16.0", features = ["derive"]}

[dev-dependencies]
tower = {version = "0.4", features = ["util"]}
