
[package]
authors = {workspace = true}
description = {workspace = true}
documentation = {workspace = true}
edition = {workspace = true}
license-file = {workspace = true}
name = "uranium"
version = {workspace = true}

[[bin]] # rename built  binary to uranium
name = "uranium"
path = "src/main.rs"

[workspace]
exclude = ["sandbox"]
members = [".", "app", "entity", "migration", "mailer"]

[dependencies]
app = {path = "app"}
axum = "0.6.20"
entity = {path = "entity"}
futures = "0.3.28"
migration = {path = "migration"}# depends on your needs
prost = {workspace = true}
sea-orm = {version = "0.12.2", features = ["macros", "debug-print", "with-uuid", "sqlx-postgres", "runtime-tokio-rustls"]}
tokio = {workspace = true, features = ["full"]}
tonic.workspace = true

[build-dependencies]
tonic-build = "0.9.2"

[workspace.package]
authors = ["Adeoye Adefemi <adefemiadeoye@yahoo.com>"]
description = "An Authentication, Authorization and Identity Management system for microservices"
documentation = "https://opeolluwa.github.io/uranium"
edition = "2021"
homepge = "https://opeolluwa.github.io/uranium"
keywords = ["gRPC", "IAM", "Authentication", "Authorization"]
exclude = ["docs"]
license-file = "./LICENSE"
name = "uranium"
version = "0.1.3"


[workspace.dependencies]
prost = "0.11.9"
tokio = {version = "1.20.1", features = ["full"]}
tonic = "0.9.2"
tonic-reflection = "0.10.0"
tower = { version = "0.4.13", features = ["full"] }
hyper = "0.14.27"
