[package]
name = "uranium"
version = "0.1.0"
license = "unlicensed"
edition = "2021"

[[bin]]
name = "bookmark"
path = "src/main.rs"


[dependencies]
anyhow = "1.0.89"
bcrypt = "0.15.1"
bincode = "1.3.3"
fred = "9.4.0"
futures = "0.3.31"
jsonwebtoken = "9.3.0"
kafka = "0.10.0"
lazy_static = "1.5.0"
log = "0.4.22"
prost = "0.13.3"
prost-types = "0.13.3"
regex = "1.11.1"
sea-orm = { version = "1.0.0-rc.5", features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tokio = { version = "1.40.0", features = ["full"] }
tonic = "0.12.3"
tonic-reflection = "0.12.3"
tower = { version = "0.5.1", features = ["full"] }
tower-http = { version = "0.6.1", features = ["trace"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
ts-rs = "10.0.0"
uranium_grpc_codegen = { git = "https://github.com/opeolluwa/uranium_grpc_codegen", tag = "v0.1.0", version = "0.1.0", default-features = false, features = [
    "server",
] }
uuid = { version = "1.10.0", features = ["v4"] }
validator = { version = "0.18.1", features = ["derive"] }
uranium_entities = { path = "./entities", version = "*" }
uranium_migration = { path = "./migration", version = "*" }


[workspace]
members = ["entities", "migration"]
package.version = "0.1.0"
package.edition = "2021"
package.description = "Uranium databse migration and entities, support PostgreSQL and Sqlite"
