[package]
name = "uranium_entities"
version = { workspace = true }
edition = {workspace = true}
description = {workspace = true}

[lib]
path = "./mod.rs"

[dependencies]
sea-orm = { version = "1.0.0-rc.5", features = [
    "runtime-tokio-rustls",
    "macros",
] }
